services:
  nginx:
    image: nginx:alpine
    container_name: nginx-basico
    ports:
      - "80:80"
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html:ro
      - ./css:/usr/share/nginx/html/css:ro
      - ./js:/usr/share/nginx/html/js:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

