services:
  nginx:
    image: nginx:alpine
    container_name: nginx-basico
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./style.css:/usr/share/nginx/html/style.css:ro
      - ./main.js:/usr/share/nginx/html/main.js:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

